# Pull image from docker hub
FROM tomcat:9-jre8

# Maintainer
LABEL maintainer="Siva Nagi Reddy Alla <siva.alla@outlook.com>"

#COPY web.xml /usr/local/tomcat/conf/
COPY demo.war /usr/local/tomcat/webapps/
